
name: Pull Request Status

on:
  pull_request_review:
    types: [submitted]

jobs:
  check_status:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

