name: Secrets

on: push

jobs:
  secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run example command
        shell: bash
        env:
          SUPER_SECRET: ${{secrets.SUPER_SECRET}}
        run: |
          echo "secrets : $SUPER_SECRET"
          echo "Command executed successfully"
